default_stages: [pre-commit]
default_install_hook_types: [pre-commit, pre-push]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: no-commit-to-branch
  - id: check-ast
  - id: check-toml
  - id: end-of-file-fixer
    stages: ["pre-commit"]
  - id: trailing-whitespace
    stages: ["pre-commit"]

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black

- repo: local
  hooks:
  - id: pyproject-flake8
    name: pyproject-flake8
    language: system
    pass_filenames: true
    entry: pflake8
    types: ["python"]

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.49"
  hooks:
  - id: check-manifest

- repo: local
  hooks:
  - id: check-missing-migrations
    name: check-missing-migrations
    entry: python /opt/netbox-dev/netbox/manage.py makemigrations netbox_data_flows --check
    language: system
    pass_filenames: false
    types: ["python"]
    stages: ["pre-push", "manual"]
  - id: check-pending-migrations
    name: check-pending-migrations
    entry: python /opt/netbox-dev/netbox/manage.py migrate netbox_data_flows --check
    language: system
    pass_filenames: false
    types: ["python"]
    stages: ["pre-push", "manual"]
  - id: run-tests
    name: run-tests
    entry: python /opt/netbox-dev/netbox/manage.py test --parallel auto netbox_data_flows
    language: system
    pass_filenames: false
    types: ["python"]
    stages: ["manual"]
    verbose: true
