---
name: 📖 Documentation Change
description: Suggest an addition or modification to NetBox Data Flows documentation
labels: ["type: documentation", "status: pending triage"]
body:
  - type: textarea
    attributes:
      label: Proposed Changes
      description: Describe the proposed changes and why they are necessary.
    validations:
      required: true
