# Generated by Django 5.2.4 on 2025-08-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_data_flows", "0001_initial_squashed_new_installations"),
        ("tenancy", "0017_natural_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dataflows",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="dataflowgroup",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dataflowgroups",
                to="tenancy.tenant",
            ),
        ),
    ]
