# Generated by Django 4.0.8 on 2022-11-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0060_alter_l2vpn_slug"),
        ("netbox_data_flows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataflow",
            name="destination_ipaddress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="dataflow",
            name="source_ipaddress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="dataflowtemplate",
            name="destination_ipaddress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="dataflowtemplate",
            name="source_ipaddress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ipam.ipaddress",
            ),
        ),
    ]
