# Generated by Django 4.0.8 on 2022-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_data_flows",
            "0002_alter_dataflow_destination_ipaddress_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dataflow",
            name="status",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="dataflowtemplate",
            name="status",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
