# Generated by Django 5.2.5 on 2025-09-02 16:22

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_data_flows", "0002_application_tenant_dataflow_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataflow",
            name="destination_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(65535),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dataflow",
            name="source_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(65535),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
