# Generated by Django 4.1.4 on 2022-12-15 15:49

from django.db import migrations, models
import utilities.json


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_flows", "0002_alter_objectalias_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="custom_field_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=utilities.json.CustomFieldJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrole",
            name="custom_field_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=utilities.json.CustomFieldJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="dataflow",
            name="custom_field_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=utilities.json.CustomFieldJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="dataflowgroup",
            name="custom_field_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=utilities.json.CustomFieldJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="objectalias",
            name="custom_field_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=utilities.json.CustomFieldJSONEncoder,
            ),
        ),
    ]
