# Generated by Django 5.2.9 on 2025-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_data_flows", "0003_allow_port_0_in_source_and_destination_ports"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrole",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
