# Generated by Django 4.0.8 on 2022-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_data_flows", "0003_dataflow_status_dataflowtemplate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataflow",
            name="status",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="dataflowtemplate",
            name="status",
            field=models.CharField(max_length=10),
        ),
    ]
