# Generated by Django 4.0.8 on 2022-11-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_data_flows",
            "0004_alter_dataflow_status_alter_dataflowtemplate_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataflow",
            name="status",
            field=models.CharField(default="enabled", max_length=10),
        ),
        migrations.AlterField(
            model_name="dataflowtemplate",
            name="status",
            field=models.CharField(default="enabled", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="dataflow",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"),
                name="netbox_data_flows_dataflow_parent_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent", None)),
                fields=("application", "name"),
                name="netbox_data_flows_dataflow_application_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowtemplate",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"),
                name="netbox_data_flows_dataflowtemplate_parent_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent", None)),
                fields=("name",),
                name="netbox_data_flows_dataflowtemplate_name",
            ),
        ),
    ]
