# Generated by Django 5.2.9 on 2025-12-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_data_flows", "0004_applicationrole_comments"),
        ("users", "0015_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="applicationrole",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="dataflow",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="dataflowgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="objectalias",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
    ]
