# Generated by Django 4.0.8 on 2022-11-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_data_flows",
            "0005_alter_dataflow_status_alter_dataflowtemplate_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="services",
        ),
    ]
