# Generated by Django 6.1 on 2026-08-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_data_flows", "0005_add_owner_fields_nb45"),
        ("users", "0015_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="applicationrole",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="dataflow",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="dataflowgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="objectalias",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
    ]
