# Generated by Django 6.1 on 2026-08-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0143_event_rule_action_registry"),
        ("netbox_data_flows", "0006_alter_application_owner_alter_applicationrole_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectalias",
            name="device_tags",
            field=models.ManyToManyField(blank=True, related_name="data_flow_device_object_aliases", to="extras.tag"),
        ),
        migrations.AddField(
            model_name="objectalias",
            name="tag_matching_rule",
            field=models.CharField(default="primary", max_length=10),
        ),
        migrations.AddField(
            model_name="objectalias",
            name="virtual_machine_tags",
            field=models.ManyToManyField(
                blank=True, related_name="data_flow_virtual_machine_object_aliases", to="extras.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="objectalias",
            index=models.Index(fields=["tag_matching_rule"], name="netbox_data_tag_mat_a37709_idx"),
        ),
    ]
