# Generated by Django 4.0.8 on 2022-11-06 21:50

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0077_customlink_extend_text_and_url"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("netbox_data_flows", "0006_remove_application_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectAliasTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="net", editable=False, max_length=5
                    ),
                ),
                ("aliased_object_id", models.PositiveBigIntegerField()),
                (
                    "aliased_object_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(
                                models.Q(
                                    ("app_label", "ipam"), ("model", "prefix")
                                ),
                                models.Q(
                                    ("app_label", "ipam"), ("model", "iprange")
                                ),
                                models.Q(
                                    ("app_label", "ipam"),
                                    ("model", "ipaddress"),
                                ),
                                _connector="OR",
                            )
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("type", "aliased_object_id"),
            },
        ),
        migrations.CreateModel(
            name="ObjectAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "size",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="net", editable=False, max_length=5
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        related_name="aliases",
                        to="netbox_data_flows.objectaliastarget",
                    ),
                ),
            ],
            options={
                "ordering": ("type", "name"),
            },
        ),
        migrations.AddConstraint(
            model_name="objectaliastarget",
            constraint=models.UniqueConstraint(
                fields=("aliased_object_type", "aliased_object_id"),
                name="netbox_data_flows_objectaliastarget_type_id",
            ),
        ),
    ]
