# Generated by Django 4.1.6 on 2023-02-19 17:28

from django.core import management
from django.db import migrations


def delete_orphaned_aliases(apps, schema_editor):
    management.call_command(
        "delete_orphaned_aliases",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_flows", "0007_remove_objectalias_size"),
    ]

    operations = [
        migrations.RunPython(
            code=delete_orphaned_aliases,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
