# Generated by Django 4.0.8 on 2022-11-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("netbox_data_flows", "0007_objectaliastarget_objectalias_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectaliastarget",
            name="aliased_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "ipam"), ("model", "prefix")),
                        models.Q(("app_label", "ipam"), ("model", "iprange")),
                        models.Q(
                            ("app_label", "ipam"), ("model", "ipaddress")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
