# Generated by Django 4.2.9 on 2024-01-21 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_data_flows", "0009_fix_empty_dfg_slugs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectaliastarget",
            options={"ordering": ("target_type", "target_id")},
        ),
    ]
