# Generated by Django 6.1 on 2026-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0144_customfield_status"),
        ("netbox_data_flows", "0009_objectalias_machine_tag_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectalias",
            name="interface_tag_operator",
            field=models.CharField(default="any", max_length=3),
        ),
        migrations.AddField(
            model_name="objectalias",
            name="interface_tags",
            field=models.ManyToManyField(
                blank=True, related_name="data_flow_interface_object_aliases", to="extras.tag"
            ),
        ),
    ]
