# Generated by Django 5.2.9 on 2026-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_data_flows", "0005_add_owner_fields_nb45"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectalias",
            name="device_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="data_flow_device_object_aliases",
                to="extras.tag",
            ),
        ),
        migrations.AddField(
            model_name="objectalias",
            name="virtual_machine_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="data_flow_virtual_machine_object_aliases",
                to="extras.tag",
            ),
        ),
    ]
