name: Upload Python Package to PyPI

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/python-build.yml
  testpypi-publish:
    name: Upload release to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/netbox-data-flows
    permissions:
      id-token: write
    steps:
      - run: mkdir dist
      - uses: actions/download-artifact@v3
        with:
          name: distributions
          path: dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
